In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Методика скринінг  (Ответы) - Ответы на форму (1).csv")
df.head()

,Отметка времени,Прізвище,Клас,Стать,Чи займаєтесь ви спортом?,"Яким видом?(Якщо ні то напишіть:""Ні"")",Питання 1. Іноді не можу справитися з бажанням нашкодити кому-небудь.,"Питання 2. Інколи можу розповсюджувати плітки про людей, яких не люблю.","Питання 3. Легко виходжу з себе, проте легко й заспокоююсь.","Питання 4. Якщо до мене не звернутись по-доброму, прохання не виконаю.",...,"Питання 66. Не вмію поставити людину на місце, навіть коли вона на це заслуговує.","Питання 67. Часто думаю, що живу неправильно.","Питання 68. Знаю людей, які можуть довести мене до бійки.",Питання 69. Не сумую через дрібниці.,"Питання 70. Мені рідко приходить в голову думка про те, що люди намагаються розізлити чи образити мене.","Питання 71. Часто просто погрожую людям, не збираючись виконувати свої погрози.",Питання 72. Останнім часом я став занудою.,Питання 73. У суперечці часто підвищую голос.,Питання 74. Намагаюся приховати погане відношення до людей.,"Питання 75. Краще погоджуся з чимось, аніж стану сперечатися."
0,19.01.2026 9:41:59,Папірник,7-г,Жіноча,1-2 рази на тиждень,Ні,"Можливо, ні",Так,Так,"Можливо, так",...,Так,Так,Так,Так,Так,Так,"Можливо, так","Можливо, ні",Так,"Можливо, так"
1,19.01.2026 9:42:06,Філяс,7-Г,Чоловіча,3 рази на тиждень,Ні,Ні,"Можливо, так",Так,Ні,...,"Можливо, ні",Ні,Ні,Ні,"Можливо, ні",Ні,Ні,Ні,Так,"Можливо, так"
2,19.01.2026 9:43:49,Катанов,7-Г,Чоловіча,3 рази на тиждень,Баскетболом,Ні,Ні,Так,"Можливо, ні",...,"Можливо, ні",Ні,Ні,Так,Так,Ні,Ні,Ні,"Можливо, ні",Так
3,19.01.2026 9:44:19,цибульська,7-Г,Жіноча,1-2 рази на тиждень,танці,"Можливо, ні","Можливо, так","Можливо, так",Ні,...,Ні,"Можливо, так",Ні,"Можливо, ні",Так,Ні,"Можливо, ні","Можливо, так","Можливо, так",Так
4,19.01.2026 9:44:30,Войтів,7-Г,Чоловіча,4 - 5 разів на тиждень,"Карате, регбі",Ні,Ні,Ні,Ні,...,"Можливо, так",Ні,Ні,Так,Ні,"Можливо, ні","Можливо, так",Ні,"Можливо, так","Можливо, так"

In [23]:
df['Прізвище'] = None
arr = np.arange(1,226)
df['Прізвище'] = arr
df['Клас'] = df['Клас'].str.replace('7','12')
df['Клас'] = df['Клас'].str.replace('8','13')
df['Клас'] = df['Клас'].str.replace('9','15')
df

,Отметка времени,Прізвище,Клас,Стать,Чи займаєтесь ви спортом?,"Яким видом?(Якщо ні то напишіть:""Ні"")",Питання 1. Іноді не можу справитися з бажанням нашкодити кому-небудь.,"Питання 2. Інколи можу розповсюджувати плітки про людей, яких не люблю.","Питання 3. Легко виходжу з себе, проте легко й заспокоююсь.","Питання 4. Якщо до мене не звернутись по-доброму, прохання не виконаю.",...,"Питання 66. Не вмію поставити людину на місце, навіть коли вона на це заслуговує.","Питання 67. Часто думаю, що живу неправильно.","Питання 68. Знаю людей, які можуть довести мене до бійки.",Питання 69. Не сумую через дрібниці.,"Питання 70. Мені рідко приходить в голову думка про те, що люди намагаються розізлити чи образити мене.","Питання 71. Часто просто погрожую людям, не збираючись виконувати свої погрози.",Питання 72. Останнім часом я став занудою.,Питання 73. У суперечці часто підвищую голос.,Питання 74. Намагаюся приховати погане відношення до людей.,"Питання 75. Краще погоджуся з чимось, аніж стану сперечатися."
0,19.01.2026 9:41:59,1,12-г,Жіноча,1-2 рази на тиждень,Ні,"Можливо, ні",Так,Так,"Можливо, так",...,Так,Так,Так,Так,Так,Так,"Можливо, так","Можливо, ні",Так,"Можливо, так"
1,19.01.2026 9:42:06,2,12-Г,Чоловіча,3 рази на тиждень,Ні,Ні,"Можливо, так",Так,Ні,...,"Можливо, ні",Ні,Ні,Ні,"Можливо, ні",Ні,Ні,Ні,Так,"Можливо, так"
2,19.01.2026 9:43:49,3,12-Г,Чоловіча,3 рази на тиждень,Баскетболом,Ні,Ні,Так,"Можливо, ні",...,"Можливо, ні",Ні,Ні,Так,Так,Ні,Ні,Ні,"Можливо, ні",Так
3,19.01.2026 9:44:19,4,12-Г,Жіноча,1-2 рази на тиждень,танці,"Можливо, ні","Можливо, так","Можливо, так",Ні,...,Ні,"Можливо, так",Ні,"Можливо, ні",Так,Ні,"Можливо, ні","Можливо, так","Можливо, так",Так
4,19.01.2026 9:44:30,5,12-Г,Чоловіча,4 - 5 разів на тиждень,"Карате, регбі",Ні,Ні,Ні,Ні,...,"Можливо, так",Ні,Ні,Так,Ні,"Можливо, ні","Можливо, так",Ні,"Можливо, так","Можливо, так"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,30.01.2026 12:44:00,221,15б,Чоловіча,Ні,Ні,"Можливо, так","Можливо, ні","Можливо, ні",Ні,...,Ні,Ні,Так,Так,"Можливо, так",Ні,Ні,"Можливо, так",Так,"Можливо, так"
221,30.01.2026 12:45:19,222,15 - Б,Чоловіча,Ні,Ні,"Можливо, ні",Ні,"Можливо, так","Можливо, ні",...,Так,"Можливо, так","Можливо, ні","Можливо, ні","Можливо, так","Можливо, ні","Можливо, ні","Можливо, так",Так,"Можливо, так"
222,30.01.2026 12:47:09,223,13-в,Жіноча,3 рази на тиждень,"Танці, баскетбол","Можливо, ні","Можливо, ні","Можливо, так","Можливо, так",...,"Можливо, так","Можливо, так","Можливо, так","Можливо, ні","Можливо, так","Можливо, так","Можливо, ні","Можливо, так","Можливо, так","Можливо, так"
223,30.01.2026 12:52:41,224,13-В,Жіноча,4 - 5 разів на тиждень,Фігурне катання,"Можливо, ні",Ні,"Можливо, так","Можливо, так",...,Ні,"Можливо, ні","Можливо, так",Так,Так,Ні,Ні,"Можливо, так","Можливо, ні","Можливо, так"
224,30.01.2026 12:53:33,225,15-Б,Чоловіча,більше 5 разів на тиждень,Ні,Так,Ні,Так,"Можливо, так",...,Так,Так,Так,Так,Ні,Ні,Так,Ні,Так,Так